env:
  - NODE_VERSION=0.10
  - NODE_VERSION=0.11

#before_install:
# - wget -P ../ https://download.srcclr.com/console/srcclr-console-latest.zip
# - unzip ../srcclr-console-latest.zip && rm ../srcclr-console-latest.zip && mv ../srcclr-console-* ../srcclr

install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - git --version
  - svn --version | head -n 1
  - npm install -g grunt-cli
  - npm install

os:
  - osx
  - linux

matrix:
  allow_failures:
    - os: osx
    - env: "NODE_VERSION=0.11"

script:
  - grunt travis
  #- echo -e '\ne4fbe422-e8fb-4d68-8d2d-714667cf59c6\n\n\n\nquit' | ../srcclr/srcclr
  #- ../srcclr/srcclr -e "scan --path $PWD"
